# -*- coding: utf-8 -*-
"""BUSI 1783- BUSINESS ANALYTICS PROJECT.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1auaSmPt05AvpdNF7dwbx6KdtlFTPoZlu
"""

from google.colab import files
uploaded = files.upload()  # select trustpilot_clean_final.csv

import pandas as pd

df = pd.read_csv('trustpilot_clean_final.csv')
print(f"Total reviews: {len(df)}")
print(df.columns.tolist())  # show column names
print(df.head())

!pip install vaderSentiment bertopic sentence-transformers umap-learn hdbscan plotly

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from scipy.stats import chi2_contingency
from vaderSentiment.vaderSentiment import SentimentIntensityAnalyzer
from bertopic import BERTopic
from sentence_transformers import SentenceTransformer
import plotly.express as px
import warnings
warnings.filterwarnings('ignore')

print("Libraries loaded")

import pandas as pd
from vaderSentiment.vaderSentiment import SentimentIntensityAnalyzer

df = pd.read_csv('trustpilot_clean_final.csv')

analyzer = SentimentIntensityAnalyzer()

def get_vader_sentiment(text):
    scores = analyzer.polarity_scores(str(text))
    compound = scores['compound']
    if compound >= 0.05:
        return 'Positive', compound
    elif compound <= -0.05:
        return 'Negative', compound
    else:
        return 'Neutral', compound

df[['Vader_Label', 'Vader_Score']] = df['Text'].apply(
    lambda x: pd.Series(get_vader_sentiment(x))
)

print("=== OVERALL SENTIMENT DISTRIBUTION ===")
print(df['Vader_Label'].value_counts())
print(f"\nPercentages:")
print(df['Vader_Label'].value_counts(normalize=True).round(3) * 100)

print("\n=== SENTIMENT BY BRAND ===")
print(pd.crosstab(df['Brand'], df['Vader_Label']))

print("\n=== SENTIMENT BY CATEGORY ===")
print(pd.crosstab(df['Category'], df['Vader_Label']))

print("\n=== AVERAGE VADER SCORE BY BRAND ===")
print(df.groupby('Brand')['Vader_Score'].mean().round(3).sort_values(ascending=False))

fig, axes = plt.subplots(2, 2, figsize=(16, 12))

# 1 Overall sentiment
colors = {'Positive': 'green', 'Negative': 'red', 'Neutral': 'grey'}
sentiment_counts = df['Vader_Label'].value_counts()
sentiment_counts.plot(
    kind='bar', ax=axes[0,0],
    color=[colors.get(x, 'blue') for x in sentiment_counts.index]
)
axes[0,0].set_title('Overall Sentiment Distribution', fontsize=13)
axes[0,0].set_xlabel('Sentiment')
axes[0,0].set_ylabel('Count')
axes[0,0].tick_params(axis='x', rotation=0)

# 2 Sentiment by brand (stacked %)
sentiment_brand = pd.crosstab(
    df['Brand'], df['Vader_Label'], normalize='index'
) * 100
sentiment_brand[['Positive','Neutral','Negative']].plot(
    kind='bar', ax=axes[0,1],
    color=['green','grey','red'],
    stacked=True
)
axes[0,1].set_title('Sentiment Distribution by Brand (%)', fontsize=13)
axes[0,1].set_xlabel('Brand')
axes[0,1].set_ylabel('Percentage')
axes[0,1].tick_params(axis='x', rotation=45)
axes[0,1].legend(loc='lower right')

# 3 Sentiment by category
sentiment_cat = pd.crosstab(
    df['Category'], df['Vader_Label'], normalize='index'
) * 100
sentiment_cat[['Positive','Neutral','Negative']].plot(
    kind='bar', ax=axes[1,0],
    color=['green','grey','red'],
    stacked=True
)
axes[1,0].set_title('Sentiment by Category (%)', fontsize=13)
axes[1,0].set_xlabel('Category')
axes[1,0].set_ylabel('Percentage')
axes[1,0].tick_params(axis='x', rotation=0)

# 4 Average VADER score by brand
df.groupby('Brand')['Vader_Score'].mean().sort_values().plot(
    kind='bar', ax=axes[1,1], color='steelblue'
)
axes[1,1].set_title('Average VADER Score by Brand', fontsize=13)
axes[1,1].set_xlabel('Brand')
axes[1,1].set_ylabel('Average Compound Score')
axes[1,1].tick_params(axis='x', rotation=45)
axes[1,1].axhline(y=0, color='red', linestyle='--')

plt.tight_layout()
plt.savefig('vader_results.png', dpi=150, bbox_inches='tight')
plt.show()
print("Saved: vader_results.png")

print("=== CHI-SQUARE TEST ===")

contingency = pd.crosstab(df['Category'], df['Vader_Label'])
print("Contingency Table:")
print(contingency)

chi2, p, dof, expected = chi2_contingency(contingency)

print(f"\nChi2 Statistic:     {chi2:.4f}")
print(f"P-value:            {p:.6f}")
print(f"Degrees of Freedom: {dof}")

if p < 0.05:
    print("\n✅ SIGNIFICANT — sentiment differences between")
    print("   ethical and fast fashion brands are NOT due to chance (p < 0.05)")
else:
    print("\n❌ NOT SIGNIFICANT — no significant sentiment difference (p > 0.05)")

print("Running BERTopic — please wait 5-10 minutes...")

docs = df['Clean_Text'].astype(str).tolist()

embedding_model = SentenceTransformer('all-MiniLM-L6-v2')

topic_model = BERTopic(
    embedding_model=embedding_model,
    min_topic_size=10,
    nr_topics='auto',
    verbose=True
)

topics, probs = topic_model.fit_transform(docs)

df['Topic'] = topics
df['Topic_Prob'] = probs

print(f"\n=== BERTOPIC RESULTS ===")
print(f"Total topics found: {len(topic_model.get_topic_info()) - 1}")
print("\nTopic Info:")
print(topic_model.get_topic_info().head(15))

print("\nTop keywords per topic:")
topic_info = topic_model.get_topic_info()
topic_info_filtered = topic_info[topic_info['Topic'] != -1].head(10)
for topic_id in topic_info_filtered['Topic'].values:
    words = topic_model.get_topic(topic_id)
    keywords = [w[0] for w in words[:8]]
    print(f"  Topic {topic_id}: {', '.join(keywords)}")

!pip install bertopic sentence-transformers # Ensure bertopic and sentence-transformers are installed

import pandas as pd
import matplotlib.pyplot as plt
from bertopic import BERTopic
from sentence_transformers import SentenceTransformer

# Re-creating dependencies for topic_model due to NameError
# This code typically resides in preceding cells (`bOdOPtyR7SMi` and `AuG6Cs-F5xIN`).
# If the kernel was restarted or cells were run out of order, these variables need to be re-initialized.
df = pd.read_csv('trustpilot_clean_final.csv') # Assuming this file exists and df was structured as before
docs = df['Clean_Text'].astype(str).tolist()

embedding_model = SentenceTransformer('all-MiniLM-L6-v2')

topic_model = BERTopic(
    embedding_model=embedding_model,
    min_topic_size=10,
    nr_topics='auto',
    verbose=True
)

# NOTE: The model needs to be fitted again if re-initialized.
# This part is crucial for the topic_model to work correctly, as `fit_transform` was called previously.
topics, probs = topic_model.fit_transform(docs)
df['Topic'] = topics # Re-assign Topic and Topic_Prob to df if df is re-loaded
df['Topic_Prob'] = probs

# Topic frequency chart
topic_info_plot = topic_model.get_topic_info()
topic_info_plot = topic_info_plot[
    topic_info_plot['Topic'] != -1
].head(10)

plt.figure(figsize=(12, 6))
plt.barh(
    topic_info_plot['Topic'].astype(str),
    topic_info_plot['Count'],
    color='steelblue'
)
plt.title('Top 10 BERTopic Topics by Frequency')
plt.xlabel('Number of Reviews')
plt.ylabel('Topic ID')
plt.tight_layout()
plt.savefig('bertopic_topics.png', dpi=150)
plt.show()
print("Saved: bertopic_topics.png")

# Interactive visualisation
try:
    fig = topic_model.visualize_topics()
    fig.write_html('bertopic_interactive.html')
    fig.show()
    print("Saved: bertopic_interactive.html")
except Exception as e:
    print(f"Interactive viz error: {e}")

print("=== TOPIC x SENTIMENT ===")
topic_sentiment = pd.crosstab(df['Topic'], df['Vader_Label'])
print(topic_sentiment[topic_sentiment.index != -1].head(15))

print("\n=== BRAND x TOPIC ===")
brand_topic = pd.crosstab(df['Brand'], df['Topic'])
print(brand_topic)

print("\n=== SENTIMENT PER TOPIC (%) ===")
topic_sent_pct = pd.crosstab(
    df['Topic'], df['Vader_Label'], normalize='index'
) * 100
print(topic_sent_pct[topic_sent_pct.index != -1].head(10).round(1))

# Topic sentiment chart
topic_sent_plot = topic_sent_pct[topic_sent_pct.index != -1].head(10)
topic_sent_plot[['Positive','Neutral','Negative']].plot(
    kind='bar', figsize=(14,6),
    color=['green','grey','red'],
    stacked=True
)
plt.title('Sentiment Distribution per Topic (%)')
plt.xlabel('Topic')
plt.ylabel('Percentage')
plt.legend(loc='lower right')
plt.tight_layout()
plt.savefig('topic_sentiment.png', dpi=150)
plt.show()
print("Saved: topic_sentiment.png")

df.to_csv('final_results.csv', index=False)
topic_model.get_topic_info().to_csv('topic_info.csv', index=False)

from google.colab import files
files.download('final_results.csv')
files.download('topic_info.csv')
files.download('vader_results.png')
files.download('bertopic_topics.png')
files.download('topic_sentiment.png')

print("All files downloaded")
print(f"\nFinal summary:")
print(f"Total reviews: {len(df)}")
print(f"Topics found: {len(topic_model.get_topic_info()) - 1}")
print(f"Sentiment distribution:")
print(df['Vader_Label'].value_counts())