# -*- coding: utf-8 -*-
"""BUSI 1783- BUSINESS ANALYTICS PROJECT_final_ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1auaSmPt05AvpdNF7dwbx6KdtlFTPoZlu
"""

# ============================================================
# CELL 1 —UPLOAD DATASET
# ============================================================

from google.colab import files

uploaded = files.upload()   # Select trustpilot_clean_final.csv

# ============================================================
# CELL 2 — IDENTIFY AND LOAD DATASET
# ============================================================

import pandas as pd

# Automatically identify the uploaded CSV
input_file = next(iter(uploaded))

print("Selected file:", input_file)

df = pd.read_csv(input_file)

print("Dataset loaded successfully.")
print("Total reviews:", len(df))
print("Columns:", df.columns.tolist())

df.head()

# ============================================================
# CELL 3 — INSTALL REQUIRED LIBRARIES
# ============================================================

!pip install -q vaderSentiment bertopic sentence-transformers umap-learn hdbscan plotly scikit-learn scipy seaborn

print("All required libraries installed successfully.")

# ============================================================
# CELL 4 — IMPORT LIBRARIES AND SETUP
# ============================================================

import re
import warnings
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from scipy.stats import chi2_contingency
from vaderSentiment.vaderSentiment import SentimentIntensityAnalyzer
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

from umap import UMAP
from hdbscan import HDBSCAN
from sentence_transformers import SentenceTransformer
from bertopic import BERTopic

warnings.filterwarnings("ignore")

print("Libraries imported successfully.")

# ============================================================
# CELL 5 — CORPUS OVERVIEW
# ============================================================

print("=== CORPUS OVERVIEW ===")

print("\nTotal reviews:", len(df))

print("\nReviews per brand:")
print(df["Brand"].value_counts())

print("\nReviews per category:")
print(df["Category"].value_counts())

print("\nRating distribution:")
print(df["Rating"].value_counts().sort_index())

# Review length
df["Review_Length"] = df["Text"].fillna("").str.split().str.len()

print("\nAverage review length by brand:")
print(df.groupby("Brand")["Review_Length"].mean().round(1))

print("\nOverall average review length:",
      round(df["Review_Length"].mean(), 1), "words")

# Rating distribution figure
plt.figure(figsize=(8, 5))

df["Rating"].value_counts().sort_index().plot(kind="bar")

plt.title("Star Rating Distribution Across Full Corpus")
plt.xlabel("Star Rating")
plt.ylabel("Count")
plt.xticks(rotation=0)

plt.tight_layout()
plt.savefig("rating_distribution.png", dpi=300, bbox_inches="tight")
plt.show()

print("Saved: rating_distribution.png")

# ============================================================
# CELL 6 — VADER SENTIMENT ANALYSIS
# ============================================================

analyzer = SentimentIntensityAnalyzer()

def get_vader_sentiment(text):

    scores = analyzer.polarity_scores(str(text))
    compound = scores["compound"]

    if compound >= 0.05:
        label = "Positive"

    elif compound <= -0.05:
        label = "Negative"

    else:
        label = "Neutral"

    return label, compound


df[["Vader_Label", "Vader_Score"]] = df["Text"].apply(
    lambda x: pd.Series(get_vader_sentiment(x))
)

print("=== OVERALL SENTIMENT DISTRIBUTION ===")

print(df["Vader_Label"].value_counts())

print("\nPercentages:")
print(
    (df["Vader_Label"].value_counts(normalize=True) * 100).round(1)
)

print("\n=== SENTIMENT BY BRAND ===")
print(pd.crosstab(df["Brand"], df["Vader_Label"]))

print("\n=== SENTIMENT BY CATEGORY ===")
print(pd.crosstab(df["Category"], df["Vader_Label"]))

print("\n=== AVERAGE VADER SCORE BY BRAND ===")
print(
    df.groupby("Brand")["Vader_Score"]
    .mean()
    .round(3)
    .sort_values(ascending=False)
)

# ============================================================
# CELL 7 — VADER VISUALISATIONS
# ============================================================

# -------------------------------
# Overall sentiment
# -------------------------------

sentiment_counts = df["Vader_Label"].value_counts()

plt.figure(figsize=(8, 5))

sentiment_counts.plot(kind="bar")

plt.title("Overall Sentiment Distribution")
plt.xlabel("Sentiment")
plt.ylabel("Count")
plt.xticks(rotation=0)

plt.tight_layout()
plt.savefig("overall_sentiment.png", dpi=300, bbox_inches="tight")
plt.show()


# -------------------------------
# Sentiment by brand
# -------------------------------

sentiment_brand = pd.crosstab(
    df["Brand"],
    df["Vader_Label"],
    normalize="index"
) * 100

cols = [
    c for c in ["Positive", "Neutral", "Negative"]
    if c in sentiment_brand.columns
]

sentiment_brand[cols].plot(
    kind="bar",
    stacked=True,
    figsize=(10, 6)
)

plt.title("Sentiment Distribution by Brand (%)")
plt.xlabel("Brand")
plt.ylabel("Percentage")
plt.xticks(rotation=45, ha="right")

plt.tight_layout()
plt.savefig("sentiment_by_brand.png", dpi=300, bbox_inches="tight")
plt.show()


# -------------------------------
# Sentiment by category
# -------------------------------

sentiment_category = pd.crosstab(
    df["Category"],
    df["Vader_Label"],
    normalize="index"
) * 100

cols = [
    c for c in ["Positive", "Neutral", "Negative"]
    if c in sentiment_category.columns
]

sentiment_category[cols].plot(
    kind="bar",
    stacked=True,
    figsize=(8, 5)
)

plt.title("Sentiment by Category (%)")
plt.xlabel("Category")
plt.ylabel("Percentage")
plt.xticks(rotation=0)

plt.tight_layout()
plt.savefig("sentiment_by_category.png", dpi=300, bbox_inches="tight")
plt.show()


# -------------------------------
# Average VADER score by brand
# -------------------------------

avg_vader = (
    df.groupby("Brand")["Vader_Score"]
    .mean()
    .sort_values()
)

plt.figure(figsize=(10, 6))

avg_vader.plot(kind="bar")

plt.axhline(y=0, linestyle="--")

plt.title("Average VADER Score by Brand")
plt.xlabel("Brand")
plt.ylabel("Average Compound Score")
plt.xticks(rotation=45, ha="right")

plt.tight_layout()
plt.savefig("average_vader_by_brand.png", dpi=300, bbox_inches="tight")
plt.show()

# ============================================================
# CELL 8 — VADER VALIDATION AGAINST STAR RATINGS
# ============================================================

def rating_to_sentiment(rating):

    if rating >= 4:
        return "Positive"

    elif rating == 3:
        return "Neutral"

    else:
        return "Negative"


df["Rating_Label"] = df["Rating"].apply(rating_to_sentiment)

accuracy = accuracy_score(
    df["Rating_Label"],
    df["Vader_Label"]
)

print("=== VADER VALIDATION ===")

print(
    f"\nAccuracy: {accuracy:.3f} "
    f"({accuracy * 100:.1f}%)"
)

print("\nClassification Report:")

print(
    classification_report(
        df["Rating_Label"],
        df["Vader_Label"],
        labels=["Positive", "Neutral", "Negative"]
    )
)

cm = confusion_matrix(
    df["Rating_Label"],
    df["Vader_Label"],
    labels=["Positive", "Neutral", "Negative"]
)

plt.figure(figsize=(8, 6))

sns.heatmap(
    cm,
    annot=True,
    fmt="d",
    cmap="Blues",
    xticklabels=["Positive", "Neutral", "Negative"],
    yticklabels=["Positive", "Neutral", "Negative"]
)

plt.title("VADER vs Star Rating Confusion Matrix")
plt.ylabel("Star Rating Label (Actual)")
plt.xlabel("VADER Label (Predicted)")

plt.tight_layout()
plt.savefig("vader_validation.png", dpi=300, bbox_inches="tight")
plt.show()

print("\nCorrelation between VADER Score and Star Rating:")

print(
    df[["Vader_Score", "Rating"]]
    .corr()
    .round(3)
)

# ============================================================
# CELL 9 — CHI-SQUARE TEST AND CRAMÉR'S V
# ============================================================

contingency = pd.crosstab(
    df["Category"],
    df["Vader_Label"]
)

print("=== CONTINGENCY TABLE ===")
print(contingency)

chi2, p, dof, expected = chi2_contingency(contingency)


def cramers_v(contingency_table):

    chi2_value = chi2_contingency(contingency_table)[0]

    n = contingency_table.to_numpy().sum()

    r, k = contingency_table.shape

    return np.sqrt(
        chi2_value /
        (n * (min(r, k) - 1))
    )


v = cramers_v(contingency)

if v < 0.1:
    effect = "negligible"

elif v < 0.3:
    effect = "small"

elif v < 0.5:
    effect = "moderate"

else:
    effect = "large"


print("\n=== CHI-SQUARE RESULTS ===")

print(f"Chi-square statistic: {chi2:.4f}")
print(f"P-value: {p:.6f}")
print(f"Degrees of freedom: {dof}")
print(f"Cramér's V: {v:.4f}")
print(f"Effect size: {effect}")

# ============================================================
# CELL 10 — BERTOPIC MODEL
# ============================================================

print("Starting BERTopic model...")

umap_model = UMAP(
    n_neighbors=15,
    n_components=5,
    min_dist=0.0,
    metric="cosine",
    random_state=42
)

hdbscan_model = HDBSCAN(
    min_cluster_size=20,
    min_samples=10,
    metric="euclidean",
    cluster_selection_method="eom",
    prediction_data=True
)

embedding_model = SentenceTransformer(
    "all-MiniLM-L6-v2"
)

topic_model = BERTopic(
    embedding_model=embedding_model,
    umap_model=umap_model,
    hdbscan_model=hdbscan_model,
    min_topic_size=20,
    nr_topics="auto",
    calculate_probabilities=False,
    verbose=True
)

docs = (
    df["Clean_Text"]
    .fillna("")
    .astype(str)
    .tolist()
)

# FIT ONCE ONLY
topics, probs = topic_model.fit_transform(docs)

df["Topic"] = topics

topic_info = topic_model.get_topic_info()

total_topics = len(
    topic_info[topic_info["Topic"] != -1]
)

outlier_count = int(
    (df["Topic"] == -1).sum()
)

outlier_pct = round(
    outlier_count / len(df) * 100,
    1
)

print("\n=== BERTOPIC RESULTS ===")

print("Total substantive topics:", total_topics)

print(
    f"Outlier documents: "
    f"{outlier_count} ({outlier_pct}%)"
)

display(topic_info)

# ============================================================
# CELL 11 — TOPIC KEYWORDS AND REPRESENTATIVE REVIEWS
# ============================================================

print("=== TOPIC DETAILS ===")

for row in topic_info.itertuples():

    if row.Topic == -1:
        continue

    words = topic_model.get_topic(row.Topic)

    keywords = [
        word[0]
        for word in words[:8]
    ]

    representative_docs = topic_model.get_representative_docs(
        row.Topic
    )

    print("\n--------------------------------------")

    print(
        f"Topic {row.Topic} "
        f"({row.Count} reviews)"
    )

    print(
        "Keywords:",
        ", ".join(keywords)
    )

    if representative_docs:

        print(
            "Representative review:",
            representative_docs[0][:200]
        )

# ============================================================
# CELL 12 — BERTOPIC FREQUENCY FIGURE
# ============================================================

topic_info_filtered = (
    topic_info[
        topic_info["Topic"] != -1
    ]
    .head(10)
)

top_n = len(topic_info_filtered)

plt.figure(figsize=(12, 6))

plt.barh(
    topic_info_filtered["Topic"].astype(str),
    topic_info_filtered["Count"]
)

plt.title(
    f"Top {top_n} BERTopic Topics by Frequency "
    f"(Total: {total_topics} topics, "
    f"{outlier_pct}% outliers)"
)

plt.xlabel("Number of Reviews")
plt.ylabel("Topic ID")

plt.tight_layout()

plt.savefig(
    "bertopic_topics.png",
    dpi=300,
    bbox_inches="tight"
)

plt.show()

print("Saved: bertopic_topics.png")

# ============================================================
# CELL 13 — TOPIC × SENTIMENT ANALYSIS
# ============================================================

topic_sentiment = pd.crosstab(
    df["Topic"],
    df["Vader_Label"]
)

print("=== TOPIC × SENTIMENT COUNTS ===")

display(
    topic_sentiment[
        topic_sentiment.index != -1
    ]
)


topic_sent_pct = pd.crosstab(
    df["Topic"],
    df["Vader_Label"],
    normalize="index"
) * 100

print("\n=== TOPIC × SENTIMENT PERCENTAGES ===")

display(
    topic_sent_pct[
        topic_sent_pct.index != -1
    ].round(1)
)


topic_sent_plot = topic_sent_pct[
    topic_sent_pct.index != -1
]

cols = [
    c for c in ["Positive", "Neutral", "Negative"]
    if c in topic_sent_plot.columns
]

topic_sent_plot[cols].plot(
    kind="bar",
    stacked=True,
    figsize=(14, 6)
)

plt.title("Sentiment Distribution per Topic (%)")
plt.xlabel("Topic")
plt.ylabel("Percentage")

plt.tight_layout()

plt.savefig(
    "topic_sentiment.png",
    dpi=300,
    bbox_inches="tight"
)

plt.show()

# ============================================================
# CELL 14 — BRAND × TOPIC CROSSTAB
# ============================================================

brand_topic = pd.crosstab(
    df["Brand"],
    df["Topic"]
)

print("=== BRAND × TOPIC CROSSTAB ===")

display(brand_topic)

# Save for checking Chapter 4 statements
brand_topic.to_csv(
    "brand_topic_crosstab.csv"
)

print("Saved: brand_topic_crosstab.csv")

# ============================================================
# CELL 15 — CORRECTED SUSTAINABILITY TERM ANALYSIS
# ============================================================
#
# CORRECTION:
# 1. Uses word boundaries
# 2. Allows legitimate morphological variants
# 3. "eco" must appear as a standalone word
# 4. Prevents recommend, second, become, economy etc.
#    from being falsely counted as "eco"
#
# ============================================================

print("=== CORRECTED SUSTAINABILITY TERM FREQUENCY ===")

stem_terms = {

    "sustainab":
        r"\bsustainab\w*",

    "ethic":
        r"\bethic\w*",

    "eco":
        r"\beco\b",

    "organic":
        r"\borganic\w*",

    "recycl":
        r"\brecycl\w*",

    "greenwash":
        r"\bgreenwash\w*",

    "environment":
        r"\benvironment\w*",

    "carbon":
        r"\bcarbon\w*",

    "fair trade":
        r"\bfair\s+trade\b",

    "climate":
        r"\bclimate\w*",

    "renewable":
        r"\brenewable\w*",

    "conscious":
        r"\bconscious\w*",

    "vegan":
        r"\bvegan\w*"
}


text_lower = (
    df["Text"]
    .fillna("")
    .astype(str)
    .str.lower()
)


term_rows = []


for label, pattern in stem_terms.items():

    mask = text_lower.str.contains(
        pattern,
        regex=True,
        na=False
    )

    count = int(mask.sum())

    percentage = round(
        count / len(df) * 100,
        1
    )

    term_rows.append(
        [label, count, percentage]
    )

    print(
        f"{label}: "
        f"{count} reviews "
        f"({percentage}%)"
    )

# ============================================================
# CELL 16 — CHECK "UNETHICAL" SEPARATELY
# ============================================================

unethical_mask = text_lower.str.contains(
    r"\bunethical\b",
    regex=True,
    na=False
)

unethical_count = int(
    unethical_mask.sum()
)

print(
    "'unethical' appears in:",
    unethical_count,
    "reviews"
)

if unethical_count > 0:

    print(
        "\nThese reviews should be interpreted separately "
        "because 'unethical' has the opposite meaning to 'ethical'."
    )

    display(
        df.loc[
            unethical_mask,
            ["Brand", "Text"]
        ]
    )

# ============================================================
# CELL 17 — CORRECTED SUSTAINABILITY TOTAL
# ============================================================

combined_pattern = "|".join(
    stem_terms.values()
)

any_sustainability_mask = text_lower.str.contains(
    combined_pattern,
    regex=True,
    na=False
)

total_with_any = int(
    any_sustainability_mask.sum()
)

total_pct = round(
    total_with_any / len(df) * 100,
    1
)

no_term_count = (
    len(df) - total_with_any
)

no_term_pct = round(
    no_term_count / len(df) * 100,
    1
)

print("=== CORRECTED RESULTS ===")

print(
    f"ANY sustainability term: "
    f"{total_with_any} reviews "
    f"({total_pct}%)"
)

print(
    f"NO sustainability term: "
    f"{no_term_count} reviews "
    f"({no_term_pct}%)"
)

# ============================================================
# CELL 18 — GENERATE CORRECTED TABLE 7
# ============================================================

term_frequency = pd.DataFrame(
    term_rows,
    columns=[
        "Term_or_Stem",
        "Reviews",
        "Percentage"
    ]
)

term_frequency.loc[
    len(term_frequency)
] = [
    "ANY Sustainability Term",
    total_with_any,
    total_pct
]

term_frequency.loc[
    len(term_frequency)
] = [
    "NO Sustainability Term",
    no_term_count,
    no_term_pct
]

print("=== CORRECTED TABLE 7 ===")

display(term_frequency)

term_frequency.to_csv(
    "sustainability_term_frequency_corrected.csv",
    index=False
)

print(
    "Saved: sustainability_term_frequency_corrected.csv"
)

# ============================================================
# CELL 19 — ADD SUSTAINABILITY RESULTS TO DATASET
# ============================================================

def find_sustainability_terms(text):

    text = str(text).lower()

    matches = []

    for label, pattern in stem_terms.items():

        if re.search(pattern, text):
            matches.append(label)

    return matches


df["Sustainability_Terms_Matched"] = (
    df["Text"]
    .fillna("")
    .apply(
        lambda x: "|".join(
            find_sustainability_terms(x)
        )
    )
)

df["Has_Sustainability_Term"] = (
    df["Sustainability_Terms_Matched"] != ""
)

df["Has_Unethical_Term"] = unethical_mask


display(
    df[
        [
            "Brand",
            "Text",
            "Sustainability_Terms_Matched",
            "Has_Sustainability_Term",
            "Has_Unethical_Term"
        ]
    ].head(10)
)

# ============================================================
# CELL 20 — CORRECTED SUSTAINABILITY FIGURE 9
# ============================================================

plot_data = term_frequency.iloc[:-2]

plt.figure(figsize=(12, 6))

plt.bar(
    plot_data["Term_or_Stem"],
    plot_data["Reviews"]
)

plt.title(
    "Sustainability Term Frequency Across Full Corpus "
    "(Corrected — Stem-Aware Matching)"
)

plt.xlabel("Sustainability Term / Stem")
plt.ylabel("Number of Reviews")

plt.xticks(
    rotation=45,
    ha="right"
)

plt.tight_layout()

plt.savefig(
    "sustainability_terms_corrected.png",
    dpi=300,
    bbox_inches="tight"
)

plt.show()

print(
    "Saved: sustainability_terms_corrected.png"
)

# ============================================================
# CELL 21 — BRAND REVIEW DATE RANGE ANALYSIS
# ============================================================

df["Date_Parsed"] = pd.to_datetime(
    df["Date"],
    errors="coerce",
    utc=True
)

date_ranges = (
    df.groupby(
        "Brand",
        as_index=False
    )
    .agg(
        Reviews=("Text", "size"),
        Start_Date=("Date_Parsed", "min"),
        End_Date=("Date_Parsed", "max")
    )
)

date_ranges["Coverage_Days"] = (
    date_ranges["End_Date"] -
    date_ranges["Start_Date"]
).dt.days + 1


date_ranges["Start_Date"] = (
    date_ranges["Start_Date"]
    .dt.strftime("%Y-%m-%d")
)

date_ranges["End_Date"] = (
    date_ranges["End_Date"]
    .dt.strftime("%Y-%m-%d")
)


print("=== REVIEW DATE RANGE BY BRAND ===")

display(date_ranges)


date_ranges.to_csv(
    "brand_review_date_ranges.csv",
    index=False
)

print(
    "Saved: brand_review_date_ranges.csv"
)

# ============================================================
# CELL 22 — SAVE ALL CORRECTED RESULTS
# ============================================================

df.to_csv(
    "final_results_corrected.csv",
    index=False
)

topic_info.to_csv(
    "topic_info.csv",
    index=False
)

brand_topic.to_csv(
    "brand_topic_crosstab.csv"
)

topic_sent_pct.to_csv(
    "topic_sentiment_percent.csv"
)

term_frequency.to_csv(
    "sustainability_term_frequency_corrected.csv",
    index=False
)

date_ranges.to_csv(
    "brand_review_date_ranges.csv",
    index=False
)

print("All corrected analysis files saved successfully.")

# ============================================================
# CELL 23 — FINAL RESULTS CHECK
# ============================================================

print("==============================================")
print("FINAL ANALYSIS RESULTS")
print("==============================================")

print(
    f"\nTotal reviews: "
    f"{len(df)}"
)

print(
    f"\nBERTopic substantive topics: "
    f"{total_topics}"
)

print(
    f"BERTopic outliers: "
    f"{outlier_count} "
    f"({outlier_pct}%)"
)

print(
    f"\nVADER accuracy: "
    f"{accuracy * 100:.1f}%"
)

print(
    f"\nChi-square: "
    f"{chi2:.2f}"
)

print(
    f"P-value: "
    f"{p:.6f}"
)

print(
    f"Cramér's V: "
    f"{v:.3f}"
)

print(
    f"\nANY sustainability term: "
    f"{total_with_any} "
    f"({total_pct}%)"
)

print(
    f"NO sustainability term: "
    f"{no_term_count} "
    f"({no_term_pct}%)"
)

print(
    f"'Unethical' reviews: "
    f"{unethical_count}"
)

print("\n==============================================")

# ============================================================
# CELL 24 — DOWNLOAD CORRECTED OUTPUT FILES
# ============================================================

from google.colab import files

files.download(
    "final_results_corrected.csv"
)

files.download(
    "sustainability_term_frequency_corrected.csv"
)

files.download(
    "brand_review_date_ranges.csv"
)

files.download(
    "brand_topic_crosstab.csv"
)

files.download(
    "topic_sentiment_percent.csv"
)

# ============================================================
# CELL 25 — SAVE AND DOWNLOAD ALL GENERATED FIGURES
# ============================================================

import os
import glob
import shutil
from google.colab import files

# Create folder for all figures
figure_folder = "All_Generated_Figures"

os.makedirs(
    figure_folder,
    exist_ok=True
)

# Find all generated PNG figures
figure_files = glob.glob("*.png")

print("=== FIGURES FOUND ===")

for figure in figure_files:

    print(figure)

    shutil.copy(
        figure,
        figure_folder
    )

# Create ZIP file
zip_file = shutil.make_archive(
    "All_Generated_Figures",
    "zip",
    figure_folder
)

print("\n======================================")
print(f"Total figures saved: {len(figure_files)}")
print("ZIP created: All_Generated_Figures.zip")
print("======================================")

# Download ZIP
files.download(
    "All_Generated_Figures.zip"
)